package interpreter.src.main.kotlin

enum class Actions {
    ADD,
    ASSIGNMENT_TO_EXISTING_VAR,
    DIVIDE,
    MULTIPLY,
    PRINT,
    SUBTRACT,
    VAR_DECLARATION,
    VAR_DECLARATION_AND_ASSIGNMENT,
    LITERAL,

    // v1.1
    CONST_DECLARATION,
    CONST_DECLARATION_AND_ASSIGNMENT,
    IF_STATEMENT,
    ELSE_STATEMENT,
    READ_INPUT,
    READ_ENV,
    BOOLEAN_OPERATION,

    // MISC
    NULL
}
