plugins {
    id 'buildlogic.kotlin-myPlugin-conventions'
}

dependencies {
    implementation project(":token")
    implementation project(":ast")
    implementation project(":lexer")
    implementation project(":parser")
    implementation project(":interpreter")
    implementation project(":formatter")
    implementation project(":linter")
    implementation project(":cli")
    implementation("org.yaml:snakeyaml:2.0")
}

tasks.withType(PublishToMavenRepository).configureEach {
    enabled = false
}
