plugins {
    id 'buildlogic.kotlin-myPlugin-conventions'
    id 'application'
}

application {
    mainClass = 'MainAppKt'
}

dependencies {
    implementation "org.jetbrains.kotlin:kotlin-stdlib"
    implementation project(":token")
    implementation project(":ast")
    implementation project(":lexer")
    implementation project(":parser")
    implementation project(":interpreter")
    implementation project(":formatter")
    implementation project(":linter")
    implementation "org.jline:jline:3.26.2"
    implementation("org.jetbrains.kotlinx:kotlinx-coroutines-core:1.7.3")
    implementation("com.github.ajalt.clikt:clikt:4.4.0")
}

tasks.named('run', JavaExec) {
    standardInput = System.in
    workingDir = rootProject.projectDir
}

tasks.named('jacocoTestCoverageVerification') {
    enabled = true
}

tasks.withType(PublishToMavenRepository).configureEach {
    enabled = false //no se publica un paquete del cli
}